### ISSUE TITLE
Flogger Kotlin JVM migrations tracker

### ISSUE THREAD

**Issue by buenaflor** [buenaflor/KFlogger#3]
List of Flogger files that are available in commonMain:
- [x] LogData
- [x] LoggerBackend
- [x] Metadata
- [x] AbstractLogger
- [x] FluentLogger
- [x] LoggingApi
- [x] LoggingScope (missing expects)
- [x] LoggingScopeProvider
- [x] LogPerBucketingStrategy
- [x] LogSite
- [x] LogSiteKey
- [x] MetadataKey (missing expects)
- [x] StackSize
- [x] LogContext
- [x] MessageParser
- [x] PrintfMessageParser and DefaultPrintfMessageParser
- [x] Parameter
- [x] AbstractBackend
- [x] BackendFactory
- [x] Platform
